os:
  - linux
services:
  - docker
language: node_js
node_js:
  - 13.5.0
jdk:
  - openjdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - '$HOME/.m2'
    - '$HOME/.yarn-cache'
    - '$HOME/.sonar/cache'
addons:
  sonarcloud:
    organization: securityrat
    token:
      secure: fE4L2eM/rtHnE/R/BzxxADVpn/BqfOOYOV8vVeGllMGrOSgudf35vpo3eLsX0Lc2Ij0a+VXwxF3a7LWWoy3MhYr4cQCUBnRjcAYnMf4kFdUjOFQr9BCde4N5SWHOJNvDFjxSYAnuPqe58WUVUrJvfBBDQFydTstZ2JRgawrUsq89G/3pZAOBBjDj3SnA5QOC5X1rOhwl33ZKOM0SbS6+hLyPkCkCRPPih1s6FsBCJ8Cj/p9+MvP1mANUMcm1KfOoZuYIvfN1mTIY/iqGT02hSlDHhitPiPCnWwPnGenIvSvpvOQNrXYjCwOnbNHCFlLzoITEdPer5Lp24IR3NuaU/lCdIrdq//re0aEv2zVdtuSPozxkEoN4O7kDLZrK5AhBKRVuoKZAqPlgoIYNumReZxW0fvgmSbp/7V20MzTJN6wiU6Z15UK1h1QJyhXo+rHuBzyGHu4R8yI57qDOwj7vS7J+3u12hSZ0h6Z3RGFb4aKXsilIzPOt6cv8PG7Xl5cekSB1quypnFXqnwlsV5YF97eFJkbE9c2GbvfdXUMVfGy6ssaPcUTNFijzCJOEHNywe8lxFxlJu+fFgEoAjdHzEZzLGNMbCL3plZNs98mlVRER0mzJzkL/DUI4IEx2Wpc7dCUKVO2+/KjYvKO4SvYFNWWwW3uWVqkONbTy/VZQgb8=
    branches:
      - master
env:
  global:
    - REPOS_SCRIPTS=$TRAVIS_BUILD_DIR/travis/scripts
    - NODE_VERSION=13.5.0
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - DOCKER_REPO=securityrat/gateway
    - secure: D/g4deuvLpX2zZ1q2rNqcXZ/ZFMovZLJBLXIO8hios/esEandWtiaEY2+vvdZsa8kaJHo9X5/8JrLlcUHZU1V0n8cQpBqed7MXJL7O2i8jE/mgKPMcaD66ZIBUc8vnn2yjeHqU6JDAFk3UVoiV4iReKYR98DsWk4wSLSn9NK2iA0GhKfP2+xIQheCNTlpaiBaXAjOTZ7VHC0Eu1aBu9ZZ4bZ73adVEovjV3r+YCHIFbj7WhoClo2eRbD+tOtDL7NCApz8Jz+3LOP5Npbb0ivrlL5RVFcpeWGWCmRhF4s53+PqNIMe74A2H4z2LEzVBIvVIhNl9aBm3ydonZWxdo0uanEsvf9+PB14oTgA2G1wC2qd4FVZqyuLbOuMT4vKnjqdTNWFjSJHBoYb8t3UeL3utBUdS/lH8LtNlpkJ/+XvsmZO0IMe+AmODre56wiJKK3ySJeEqemOs2tRA04xKWAsxdovafA/2zUZpdmjhIMw2jJkeQ0L9TIGZ8iyy6/Xx6tFZFKRr1boOg15D3uq3wXlEAPvzadSlU/Ae+9DlNPTAvLfxy0AtIQJxYlrbhn8qJ0bvhraBzdXd496aQbUl8hWuPpI9Lk5u4qUZVrFoSEF267KDjkrPUKhrJL93glELMfOcXpuD5h/1vj38Dd73K5UIDJ4uZjIXzN82Vu0SKiE+M=
    - secure: fJ2l07GcIc3rNrTM6S2TMmbZBwcI4qaaI1H5sgsy7+UX8bU5eOUOQqN486TLOn07NhvUNlSoFrd3KGHseMttifNlM2h/GLOe96Nlq06Y3zQsFw8UIytKK9waeEpXXPLQwIG5QOvWeHtLZyDYK5FhVo8ax21oG1i42ROUlidIc7/xeqD1pDxo13a/s8qadY6Gw9PnznZr4SpcsZ0q+EyWGDlXlbim7Bu0CwxYrWfNmYhy8F+doYg7+3xsqMwEOFRf5d6MVc+X0oRXYpTOaVHsjRw7o5gxEhfdQmYwha3Cc/41N/57ybmNSvU4kFMFOIy+/YAkVmE5gXYJXk57pJOBOENVKb7LT4M48TrTj+P4WJrvbzgo9SCZLMaE6COoiNxQAwNJLbzB59SgKY+UP2z4cXFm+l3eWcYzhi2yzVP47w5rd3oe+M2wTXTp1UsYuw1lMqt0vkiwgrQnyluemLKNwhr1eQEO529tdbmcotyRY8/848esJfFduZF31EvCA1LUFGGqPGJ8pQEhRh2ErOpN21L7lU5CcQiCGKUMQ47jjItx4X8LLIpT4Vvj7eZ6du3XQugN7ZbZ3yq9f/zC6hB6yQLFTyRcDKTaZT0A0TWhddOXYEL6Nz/7NH+uu2wo46PKdk4iUs51P5d3hAn4540kXco2IC0leCLCbIrlPWF+nDs=
before_install:
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install
script:
  - chmod +x mvnw
  - './mvnw clean'
  - yarn test
  - './mvnw test sonar:sonar'
before_deploy:
  - './mvnw package -Pprod -DskipTests -Ddocker.repository=$DOCKER_REPO'
deploy:
  provider: script
  script: bash $REPOS_SCRIPTS/docker_push
  on:
    branch: master
    condition: '-n $TAG_NAME'
notifications:
  email:
    on_success: change
    on_failure: always
